### ISSUE TITLE
Mini issues 

### ISSUE THREAD

**Issue by JSinfant** [codewithvoid/AskDevs#114]
![Screenshot_20221211-080706__02](https://user-images.githubusercontent.com/118141483/206884255-229f4034-e8de-47d7-8e1e-abd09fd50d70.jpg)
![Screenshot_20221211-080706__01](https://user-images.githubusercontent.com/118141483/206884264-95f4049e-b5a3-41d6-ac07-b54cdbdb400e.jpg)

Hi Void and Contributors! Kudos to your team work!!

I was going through this platform using an android phone and found these two.
1. The "data science" and "devops" fields are next to each other while rest of the fields are listed in vertical list format.
2. The scaling seems bit out of order towards the left side of the screen.

 Please ignore if this was not something to be reported. Thank You!

**Comment by codewithvoid** [comment]
Thanks for reporting @JSinfant.

@PriteshKiri Will this be fixed with your alignment changes?

**Comment by devvsakib** [comment]
@codewithvoid you can assign me

**Comment by RakeshSangem** [comment]
Hello @devvsakib, if the issues are resolved in the merged PR, please close this issue as completed.

**Comment by devvsakib** [comment]
@RakeshSangem 

i solved but he told me to revert change, so i just added my profile json. im not fixing this bug

**Comment by celomary** [comment]
hello can i take this issue

**Comment by codewithvoid** [comment]
@celomary yes please. thank you!
