### ISSUE TITLE
Unnecessarily reload

### ISSUE THREAD

**Issue by elite16op** [codewithvoid/AskDevs#161]
I was going through this on my laptop while i encountered that the page reload whenever i click on the askdev symbol and it's doing nothing which isn't a big bug but i guess it wasn't supposed to be there.
Please ignore if this was not something to be reported.
[screen-capture (10).webm](https://user-images.githubusercontent.com/111674354/209782148-654e4482-d598-45bb-8812-cb2093a993c6.webm)

**Comment by codewithvoid** [comment]
Thanks for raising @elite16op but this behaviour is intended to deselect your category selections.

**Comment by celomary** [comment]
is this issue still open, and also what should happen if someone click on the header logo

**Comment by codewithvoid** [comment]
@celomary same as current behaviour. Closing this to avoid confusion.
