### ISSUE TITLE
feat: add footer section

### ISSUE THREAD

**Issue by codewithshubhi** [codewithvoid/AskDevs#167]
Add footer section with links/forms to 
* Github contribution repo
*  Contact for support 
*  Copyright
*  Documentation/Blogs

**Comment by codewithvoid** [comment]
Thanks for raising! Will pick up as I have bandwidth.

**Comment by Anuragwagh** [comment]
Can I work on this?

**Comment by codewithvoid** [comment]
@Anuragwagh sure. Thanks! Assigned it to you.

**Comment by codewithvoid** [comment]
@Anuragwagh are you working on this one?

**Comment by Anuragwagh** [comment]
I'm working on it; in fact, my exams are underway, and my final paper is due tomorrow; I'll complete it as soon as possible after the exams are completed.

**Comment by codewithvoid** [comment]
@Anuragwagh alright. thanks for the update.

**Comment by HectorShaw** [comment]
Do let me know if it still needs to be completed.

**Comment by Anuragwagh** [comment]
Hello @HectorShaw , The issued task has been completed.

**Comment by HectorShaw** [comment]
Oh, I saw it was still open yesterday, so I got confused. No issues

**Comment by codewithvoid** [comment]
@HectorShaw if you are still looking to contribute - you can pick up #170

**Comment by codewithvoid** [comment]
Fixed in #200
