### ISSUE TITLE
feat: add topic tags to card

### ISSUE THREAD

**Issue by EmmanuelOmoiya** [codewithvoid/AskDevs#170]
Add programming language to the profile card beneath the user role

**Comment by codewithvoid** [comment]
Yes that feature is in pipeline. Will keep this open until it's merged.

**Comment by EmmanuelOmoiya** [comment]
Alright

**Comment by ArkaPrabhaChowdhury** [comment]
I am currently working on this issue. I have a query, a volunteer can have multiple slugs where each slug has different topics. So which topics should I showcase on the card?

**Comment by EmmanuelOmoiya** [comment]
You should look for any slug with the string "programming" and the map out the topics to the card ui

**Comment by codewithvoid** [comment]
Exactly. You just need to show tags specific to selected category. By default - don't show any tags.

Thanks @EmmanuelOmoiya for clarifying.

**Comment by ArkaPrabhaChowdhury** [comment]
> Exactly. You just need to show tags specific to selected category. By default - don't show any tags.
> 
> Thanks @EmmanuelOmoiya for clarifying.

Hey Void! I think I am done with the code but it is not reflecting when I am running the code on my local system. What am I missing? Any change at all is not being reflected on the localhost.
