### ISSUE TITLE
[docs] link to CODE_OF_CONDUCT.md in readme is not working

### ISSUE THREAD

**Issue by samyabrata-maji** [codewithvoid/AskDevs#172]
link to CODE_OF_CONDUCT.md in readme is not working

**Comment by codewithshubhi** [comment]
@samyabrata-maji It looks fine for me, can you share link or screenshot.

**Comment by samyabrata-maji** [comment]
<img width="606" alt="Screenshot 2023-01-08 191151" src="https://user-images.githubusercontent.com/116789799/211199375-c724ac2d-b1fb-44ed-8fec-3fedf6a209c5.png">
<img width="960" alt="Screenshot 2023-01-08 191243" src="https://user-images.githubusercontent.com/116789799/211199378-6095efea-350d-494b-872d-0e0096664ced.png">

**Comment by samyabrata-maji** [comment]
change the url to https://github.com/codewithvoid/AskDevs/blob/main/CODE_OF_CONDUCT.md

**Comment by codewithvoid** [comment]
Thanks for raising @samyabrata-maji. Yes it's broken for me too.

We can use above url link or can change url name to `CODE_OF_CONDUCT.md`. (didn't try latter though)

**Comment by samyabrata-maji** [comment]
@codewithvoid The latter works

**Comment by samyabrata-maji** [comment]
This issue is fixed
