### ISSUE TITLE
Update project description 

### ISSUE THREAD

**Issue by ibrahimraimi** [codewithvoid/AskDevs#201]
**Change the project description from:** 

![Web capture_28-1-2023_16118_github com](https://user-images.githubusercontent.com/66981941/215275320-e8045d13-36a7-41f4-b676-61af3200b530.jpeg)

**To:** 

AskDevs is a community for developers to ask questions and get answers about software development.
Tweet your technical questions to our tech Twitter volunteers.

**Why is the change important?**

It is important because it provides users with a clear understanding of what the project is, what it does, and how it can be used.

**Comment by ArkaPrabhaChowdhury** [comment]
I would like to make this change. Please assign it to me.

**Comment by codewithvoid** [comment]
@ibrahimraimi thanks for raising this. 

I understand as it's a community of developers, it makes sense to restrict scope to software development. But we intend to include non coding scopes such as technical writing, public speaking, etc. I agree it can be phrased better. 

With #170 users will have more context  on what can they ask volunteers. @ArkaPrabhaChowdhury does it interest you?

Keep suggestions coming :)

**Comment by ArkaPrabhaChowdhury** [comment]
> @ibrahimraimi thanks for raising this. 
> 
> I understand as it's a community of developers, it makes sense to restrict scope to software development. But we intend to include non coding scopes such as technical writing, public speaking, etc. I agree it can be phrased better. 
> 
> With #170 users will have more context  on what can they ask volunteers. @ArkaPrabhaChowdhury does it interest you?
> 
> Keep suggestions coming :)

Yes it does interest me.
