### ISSUE TITLE
@UbaidRussell profile image url is broken

### ISSUE THREAD

**Issue by codewithvoid** [codewithvoid/AskDevs#202]
Replace it with twitter/github image url instead in their [profile details](https://github.com/codewithvoid/AskDevs/blob/main/data/users/UbaidRussell.json)

![image](https://user-images.githubusercontent.com/104728441/215282149-b5d54c6f-6bdf-4106-b2e6-becb011ff649.png)

**Comment by ArkaPrabhaChowdhury** [comment]
@codewithvoid Is this issue fixed?

**Comment by ArkaPrabhaChowdhury** [comment]
Hey @codewithvoid 

![image](https://user-images.githubusercontent.com/92904175/216837271-593823a7-b012-4e52-bf54-b587f1b9b538.png)

Same issue with several other images.

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury yes these keep occurring will fix those too.

**Comment by ArkaPrabhaChowdhury** [comment]
@codewithvoid Are you working on this? I know another dev who can work on this issue if required.

**Comment by codewithvoid** [comment]
Not rn. You can create new issue mentioning invalid cards and assign it to them
