### ISSUE TITLE
Data Overflow Beyond Card UI

### ISSUE THREAD

**Issue by JasonDsouza212** [codewithvoid/AskDevs#218]
When **three or more topics** are added under the slug, they extend beyond the **profile user interface**
![Screenshot from 2023-02-08 11-10-27](https://user-images.githubusercontent.com/74404894/217444387-a686eeb5-000d-4e46-a697-8e4acb0b0338.png)
# To overcome this problem we can :
- **Limit the topics to atmost 3**
- **Or can make changes in the UI to scale any number of topics**

**Comment by ArkaPrabhaChowdhury** [comment]
@codewithvoid Should I try to fix this one?

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury Yes. Thank you!

**Comment by ArkaPrabhaChowdhury** [comment]
@codewithvoid I have tried to change the UI and I have come to the conclusion that we have 3 ways to do this. 

- Increase width of every card.
- Change Data Structures and Algorithms to a single word DSA and Data structures to DS. (That's the only place the issue occurs)
- Allow pills to go to a new line.

Which one should we go with? Open to any other suggestions too.

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury Let's go with option 2 and use small tags going forward.

**Comment by JasonDsouza212** [comment]
- Yup It should be mentioned in the **readme file** not to use **more than 3 topics** 
- and whichever topic is greater than 8 characters should be added in the  **small tags**
