### ISSUE TITLE
Krishna Sarathi Ghosh's profile image is broken

### ISSUE THREAD

**Issue by Gagan1708** [codewithvoid/AskDevs#225]
![image](https://user-images.githubusercontent.com/89629223/218466088-7693cf6f-86f7-4384-a786-5681bacb9310.png)

I wanted to fix the issue, could you please assign the issue.

**Comment by the-protechtron** [comment]
Hi there, I've found out that the image address doesn't exist but functions the same with proper addresses
<img width="1440" alt="Screenshot 2023-02-13 at 10 26 40 PM" src="https://user-images.githubusercontent.com/116338861/218522187-8aa82960-1aa3-4ea8-85e4-d07cbb90f6f3.png">
