### ISSUE TITLE
Bug: unable to de-select any category after choosing any one.

### ISSUE THREAD

**Issue by shubhamku044** [codewithvoid/AskDevs#260]
So, once the web app is opened, We can able to select any category to see the developers. But we can not de-select it. We need to refresh the page.

**Comment by codewithvoid** [comment]
@shubhamku044 you can click on the logo to refresh the page.

Do you have any other recommendation?

**Comment by codewithvoid** [comment]
Hm. I like the having a toggle behaviour. Let's implement that.

**Comment by shubhamku044** [comment]
yes, Please assign this to me.

**Comment by codewithvoid** [comment]
Change works perfectly. Thanks @shubhamku044. Closing this.

**Comment by shubhamku044** [comment]
You're welcome.
