### ISSUE TITLE
Background Color Gradient is not covering up the whole page

### ISSUE THREAD

**Issue by prakhartiwari0** [codewithvoid/AskDevs#34]
## Screenshot
![image](https://user-images.githubusercontent.com/65062036/203845895-56afd7cd-42f2-452a-964a-fa84a6cd125c.png)
The background gradient is not covering the complete website, which is not a good thing.

**Comment by codewithvoid** [comment]
Right. Thanks for reporting.

**Comment by prakhartiwari0** [comment]
My pleasure!
