### ISSUE TITLE
Logo is needed

### ISSUE THREAD

**Issue by Kellsonphilips** [codewithvoid/AskDevs#44]
A logo for the website is also needed which will function as a refresh button too.

**Comment by codewithvoid** [comment]
How about current title in the header? Should we add refresh link to that?

**Comment by Kellsonphilips** [comment]
Since it won't be fixed then it can't function as a link because it disappears. And for readability/accessibility, nobody will know it also serves as a route to the home screen pr refresh. A native home button would do or better still a logo that is absolute.

**Comment by codewithvoid** [comment]
@PriteshKiri Done. Thank you!

**Comment by PriteshKiri** [comment]
Have added a PR "css_change" for this issue.

**Comment by codewithvoid** [comment]
@Kellsonphilips Both the concerns have been fixed in #95 #113. PTAL.

**Comment by Kellsonphilips** [comment]
I've seen that

**Comment by Kellsonphilips** [comment]
Good one
