### ISSUE TITLE
For better positioning of the card items

### ISSUE THREAD

**Issue by satyam73** [codewithvoid/AskDevs#54]
Hello @codewithvoid,
While I was looking your site which is awesome initiative by you I figured out this points, which can be improved to give user a more better experience.

- The cards are getting one onto other at certain breakpoints. Here's the image for better demonstration.
![image](https://user-images.githubusercontent.com/85296770/204101355-702878bd-222c-4b36-a279-4a4bb710e5d6.png)

- Also in mobile view card are aligned towards left which may be can improved by centering the cards. Here's the image reference for this.
![image](https://user-images.githubusercontent.com/85296770/204101438-69c3616f-1341-49ac-8f70-ee52f0b0e9a1.png)

**Thanks!**

**Comment by codewithvoid** [comment]
Thanks for pointing it out @satyam73 . Triaged.

**Comment by codewithvoid** [comment]
Fixed in #113
