### ISSUE TITLE
Conflicting hover colors and no transition on hover activity

### ISSUE THREAD

**Issue by nkirukka** [codewithvoid/AskDevs#62]

**Comment by codewithvoid** [comment]
Hi @nkirukka. Can you please add more details? What's breaking and proposed intended behaviour?

**Comment by codewithvoid** [comment]
@nkirukka friendly ping. Can you please clarify the issue. Use screengrab if possible.

**Comment by accodes21** [comment]
I have already removed this conflicted hover colors, and The PR is already merged so you can close this issue

**Comment by codewithvoid** [comment]
Thanks @accodes21. Closing this.
