### ISSUE TITLE
Domain is too long. We can solve this by.

### ISSUE THREAD

**Issue by Anas-Dew** [codewithvoid/AskDevs#66]
Recently i've knew about Freenom which gives .tk, .ml etc. domains for free and they are secure too. You can add it to vercel. I've account on freenom let me know if this sounds good to you.

**Comment by codewithvoid** [comment]
Project is in beta atm and plan is to move it to a custom domain later. Meanwhile will stick with current domain name.

Thanks @Anas-Dew for sharing your concern.

**Comment by Anas-Dew** [comment]
ok thanks!
