### ISSUE TITLE
There's no title on page or any SEO practices.

### ISSUE THREAD

**Issue by Anas-Dew** [codewithvoid/AskDevs#78]
- The page must have title, description, meta tags, meta description, meta title tag in head section

**Comment by RakeshSangem** [comment]
Hey @Anas-Dew, thanks for bringing up this issue; we'll have a look at it.

**Comment by Anas-Dew** [comment]
it was my reposibility to report as a contributor. 😄. Also try to make user interface look more good and reponsive.
