### ISSUE TITLE
Community Standards could be set up

### ISSUE THREAD

**Issue by AldrinSeanPereira** [codewithvoid/AskDevs#80]
I noticed that the community standards tab (under Insights) showed some things that could be fixed 
for example, the code of conduct 

perhaps we can add these or you can help me to fix these :)

**Comment by RakeshSangem** [comment]
Hello, @AldrinSeanPereira We appreciate you bringing up this issue. We'll look into that.

**Comment by codewithvoid** [comment]
It's in the pipeline. Thanks for pointing out.

**Comment by codewithvoid** [comment]
@AldrinSeanPereira Added this in #102 .
