### ISSUE TITLE
Size of First Container.

### ISSUE THREAD

**Issue by Saurav-Pant** [codewithvoid/AskDevs#86]
![Screenshot (247)](https://user-images.githubusercontent.com/103263909/204956242-e427bd3a-4b4d-4563-9832-6d6e76c0874a.jpg)

**Comment by RakeshSangem** [comment]
Hey @Saurav-Pant thanks for raising this issue. We will look into that.👍

**Comment by Saurav-Pant** [comment]
my pleasure @RakeshSangem

**Comment by PriteshKiri** [comment]
This issue has been fixed. @codewithvoid you can close this.

**Comment by codewithvoid** [comment]
Thanks for pointing @PriteshKiri .  

#95 fixed this.
