### ISSUE TITLE
Need to add a favicon

### ISSUE THREAD

**Issue by PriteshKiri** [codewithvoid/AskDevs#94]
Have created a basic Favicon for the website. You can assign this to me, I'll update this on the code.
[favicon.zip](https://github.com/codewithvoid/AskDevs/files/10142040/favicon.zip)

**Comment by codewithvoid** [comment]
Awesome. Thanks Pritesh!

**Comment by PriteshKiri** [comment]
Have added a PR "add_favicon" for this issue.

**Comment by codewithvoid** [comment]
Fixed in #95
