### ISSUE TITLE
Alignment of the Home Page

### ISSUE THREAD

**Issue by itisrizu** [codewithvoid/AskDevs#96]
![Screenshot 2022-12-04 143711](https://user-images.githubusercontent.com/14951168/205482668-63037faa-45a1-4578-98f9-c24c1bbc999a.jpg)

The home page looks good being left aligned but the left margin should be corrected.

**Comment by codewithvoid** [comment]
Yes. Thanks for raising this @itisrizu .

**Comment by PriteshKiri** [comment]
I'll fix this, @codewithvoid can you assign this to me.

**Comment by codewithvoid** [comment]
Thanks @PriteshKiri . Fixed in #113.
