### ISSUE TITLE
Fix h1 tag and Add dropdown for filters.

### ISSUE THREAD

**Issue by Anas-Dew** [codewithvoid/AskDevs#99]
Hey,

1. for h1 tag look to big for mobile screen. make it a little short for example. 2rem looks better on mobile and desktop as well.

2. for filters, i would suggest adding dropdowns to make UI minimal and good for mobile users.

**Comment by codewithvoid** [comment]
@PriteshKiri thoughts?

**Comment by PriteshKiri** [comment]
Agreed! We need to improve the mobile version of Askdevs.
- Need to reduce the font size of the header text.
- We can either reduce the font size of the filters to make it fit well or can make a dropdown as suggested.
- Need to reduce the volunteer card size for the mobile version such that we can fit at least 2 cards in each row.
